#!/usr/bin/env bash
# Stamp the CSS/JS links with a hash of their contents, then commit and push.
#
# GitHub Pages serves index.html with max-age=600 but styles.css and main.js
# with max-age=14400. Without this, a deploy gives visitors new HTML alongside
# four-hour-old CSS and JS — which looks like the site is broken. Hashing the
# URL means a changed file is simply a different URL and can never be stale.
set -euo pipefail
cd "$(dirname "$0")"

css=$(md5 -q styles.css | cut -c1-8)
js=$(md5 -q main.js | cut -c1-8)

# every top-level page, so a newly added one can never ship unstamped
for f in *.html; do
  perl -pi -e "s{href=\"styles\.css(\?v=[0-9a-f]+)?\"}{href=\"styles.css?v=$css\"}g" "$f"
  perl -pi -e "s{src=\"main\.js(\?v=[0-9a-f]+)?\"}{src=\"main.js?v=$js\"}g" "$f"
done
echo "stamped  css=$css  js=$js"

# Regenerate sitemap.xml so lastmod always reflects the files themselves.
# Hand-maintained dates go stale the moment anyone forgets, and a wrong
# lastmod teaches crawlers to distrust the whole file.
python3 - <<'SITEMAP'
import pathlib, datetime
PAGES = [
    ("index.html",   "https://vrbroomrental.com/",        "monthly", "1.0"),
    ("gallery.html", "https://vrbroomrental.com/gallery", "monthly", "0.7"),
    ("contact.html", "https://vrbroomrental.com/contact", "yearly",  "0.8"),
    ("sitemap.html", "https://vrbroomrental.com/sitemap", "yearly",  "0.2"),
    ("privacy.html", "https://vrbroomrental.com/privacy", "yearly",  "0.3"),
]
out = ['<?xml version="1.0" encoding="UTF-8"?>',
       "<!-- Generated by deploy.sh; lastmod comes from each file's own timestamp. -->",
       '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for f, loc, freq, pri in PAGES:
    path = pathlib.Path(f)
    if not path.exists():
        continue
    mod = datetime.date.fromtimestamp(path.stat().st_mtime).isoformat()
    out += ["  <url>", f"    <loc>{loc}</loc>", f"    <lastmod>{mod}</lastmod>",
            f"    <changefreq>{freq}</changefreq>", f"    <priority>{pri}</priority>", "  </url>"]
out.append("</urlset>")
pathlib.Path("sitemap.xml").write_text("\n".join(out) + "\n", encoding="utf-8")
print("sitemap  %d urls" % len(PAGES))
SITEMAP

if [ -z "$(git status --porcelain)" ]; then
  echo "nothing to commit"; exit 0
fi

git add -A
git -c user.email="info@vrbroomrental.com" -c user.name="VRB Room Rental" \
    commit -q -m "${1:-Update site}"
git push -q origin main
echo "pushed $(git rev-parse --short HEAD)"
